apiVersion: v1
kind: Service
metadata:
  name: dov-bear-service
  namespace: vader
spec:
  type: NodePort
  selector:
    app: dov-bear
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
