apiVersion: v1
kind: Pod
metadata:
  name: dov-bear-pod
  namespace: vader
  labels: 
    app: dov-bear
spec:
  containers:
  - name: dov-bear-container
    imagePullPolicy: IfNotPresent
    image: ghcr.io/mayday77-77/dov-bear:v1
    ports:
    - containerPort: 3000
    envFrom:
    #- configMapRef:
    #    name: dov-bear-cm 
    - secretRef:
        name: dov-bear-secret 

