apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggns-pvc
  namespace: bggns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  
