apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggns-app-deployment
  namespace: bggns
  labels:
    name: bggns-app-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bggns-app
  template:
    metadata:
      labels:
        app: bggns-app
    spec:
      containers:
      - name: bggns-app-container
        imagePullPolicy: IfNotPresent
        image: stackupiss/bgg-backend:v2
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: bggns-secret
        - configMapRef:
            name: bggns-cm
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP


