apiVersion: v1
kind: Service
metadata:
  name: bggdb-app-svc
  namespace: bggns
spec:
  type: LoadBalancer
  selector:
    app: bggns-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
