apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deployment
  namespace: vader
  labels:
    name: dov-bear-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov-bear
  template:
    metadata:
      labels:
        app: dov-bear
    spec:
      containers:
      - name: dov-bear-container
        image: ghcr.io/mayday77-77/dov-bear:v1
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: dov-bear-secret

